mysite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView, RedirectView


# --import all module in order to call full view function name--
import django.contrib.auth.views
import views
import restaurants.views

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^menu/(?P<pk>\d+)/$', restaurants.views.MenuView.as_view()),
    url(r'^restaurants_list/$',
        login_required(restaurants.views.RestaurantsView.as_view()),
        name='restaurants-list'),
    url(r'^users_list/$', login_required(restaurants.views.list_users)),
    url(r'^comment/(?P<pk>\d+)/$',
        restaurants.views.CommentView.as_view(), name='comment-view'),
    url(r'^accounts/login/$', views.custom_login, name='accounts-login'),
    url(r'^accounts/logout/$', django.contrib.auth.views.logout,
        name='accounts-logout'),
    url(r'^vote/$', restaurants.views.vote),
    url(r'^update/comment/(?P<pk>\d+)/$',
        restaurants.views.CommentUpdate.as_view(), name='comment-update'),
    url(r'^delete/comment/(?P<pk>\d+)/$',
        restaurants.views.CommentDelete.as_view(), name='comment-delete'),
    url(r'^$',
        TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^accounts/register/$', views.register),
    url(r'^android-chrome-192x192\.png$',  # favicon for Android Chrome
        RedirectView.as_view(url='/static/favicons/android-chrome-192x192.png',
                             permanent=True)),
    url(r'^android-chrome-512x512\.png$',  # favicon for Android Chrome
        RedirectView.as_view(url='/static/favicons/android-chrome-512x512.png',
                             permanent=True)),
]

if settings.DEBUG:  # for practice usage
    urlpatterns += [
        url(r'^welcome/$', views.welcome),
        url(r'^meta/$', restaurants.views.meta),
        url(r'^set_c/$', restaurants.views.set_c),
        url(r'^get_c/$', restaurants.views.get_c),
        url(r'^use_session/$', restaurants.views.use_session),
        url(r'^session_test/$', restaurants.views.session_test),
    ]

restaurants/models.py
from django.db import models
from django.db import connection

from django.contrib.auth.models import User


class Restaurant(models.Model):
    name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=15)
    address = models.CharField(max_length=50, blank=True)

    def __unicode__(self):
        return self.name


class FoodManager(models.Manager):

    def sfood_order_by_price(self):
        return self.filter(is_spicy=True).order_by('price')

    def cheap_food_num(self):
        return self.filter(price__lte=100).count()

    def get_120_food(self):  # use SQL to get DATA.
                            # Need to import connection from django.db
        cursor = connection.cursor()
        cursor.execute("""
            SELECT name
            FROM restaurants_food
            WHERE price=120
        """)
        return [result[0] for result in cursor.fetchall()]


class SpicyFoodManager(models.Manager):
    def get_queryset(self):
        return super(SpicyFoodManager, self).get_queryset(
        ).filter(is_spicy=True)


class NotSpicyFoodManager(models.Manager):
    def get_queryset(self):
        return super(NotSpicyFoodManager, self).get_queryset(
        ).filter(is_spicy=False)


class Food(models.Model):
    name = models.CharField(max_length=20)
    price = models.DecimalField(max_digits=3, decimal_places=0)
    comment = models.CharField(max_length=50, blank=True)
    is_spicy = models.BooleanField(default=False)
    restaurant = models.ForeignKey(Restaurant)
    objects = FoodManager()
    s_objects = SpicyFoodManager()
    ns_objects = NotSpicyFoodManager()

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['price']


class Comment(models.Model):
    content = models.CharField(max_length=255)
    visitor = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    date_time = models.DateTimeField()
    restaurant = models.ForeignKey(Restaurant)

    userUpVotes = models.ManyToManyField(
        User, blank=True, related_name='threadUpVotes')
    userDownVotes = models.ManyToManyField(
        User, blank=True, related_name='threadDownVotes')

    thisUserUpVote = models.BooleanField(default=False)
    thisUserDownVote = models.BooleanField(default=False)

    def __unicode__(self):
        return self.content

    def get_total_votes(self):
        total = self.userUpVotes.count() - self.userDownVotes.count()
        return int(total)

    class Meta:
        ordering = ['id']
        permissions = (
            ("can_comment", "Can comment"),
        )

restaurants/forms.py
from django import forms


class CommentForm(forms.Form):
    visitor = forms.CharField(max_length=20,
                              widget=forms.TextInput(
                                  attrs={'readonly': 'readonly',
                                         'style': 'background-color: #ffffb3'}))
    email = forms.EmailField(max_length=40, required=False,
                             label='E-mail',
                             widget=forms.EmailInput(attrs={'size': "35", }))
    content = forms.CharField(max_length=200, widget=forms.Textarea())

restaurants/views.py
from django.shortcuts import render_to_response, render, get_object_or_404
from django.http import HttpResponse
from django.http import HttpResponseRedirect, Http404
from django.utils import timezone
from django.template import RequestContext
from django.contrib.sessions.models import Session
from django.contrib import auth
from django.contrib.auth.decorators import (login_required,
                                            user_passes_test,
                                            permission_required)
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.utils.decorators import method_decorator
from django.views.generic.edit import FormView, DeleteView, UpdateView
from django.core.urlresolvers import reverse, reverse_lazy
from django.core.exceptions import PermissionDenied

from restaurants.models import Restaurant, Comment, Food
from restaurants.forms import CommentForm


def list_users(request):
    users = auth.models.User.objects.all()
    return render(request, 'users_list.html', locals())


def user_can_comment(user):
    return (user.is_authenticated() and
            user.has_perm('restaurants.can_comment'))


class PermissionMixin(object):  # require request.user match comment creater

    def get_object(self, *args, **kwargs):
        obj = super(PermissionMixin, self).get_object(*args, **kwargs)

        if not obj.visitor == self.request.user.username:
            raise PermissionDenied()
        else:
            return obj


class MenuView(DetailView):
    model = Restaurant
    template_name = 'menu.html'
    context_object_name = 'restaurant'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(MenuView, self).dispatch(request, *args, **kwargs)

    def get(self, request, pk, *args, **kwargs):
        try:
            return super(MenuView, self).get(self, request, pk=pk,
                                             *args, **kwargs)
        except Http404:
            return HttpResponseRedirect('/restaurants_list/')


class RestaurantsView(ListView):

    model = Restaurant
    template_name = 'restaurants_list.html'
    context_object_name = 'restaurants'


class CommentUpdate(PermissionMixin, FormView, SingleObjectMixin):

    form_class = CommentForm   # didn't use UpdateView because of CommentForm
    template_name = 'comment_update_form.html'

    model = Comment            # provide by SingleObjectMixin
    context_object_name = 'c'  # provide by SingleObjectMixin

    def get_success_url(self):
        self.object = self.get_object()
        return reverse('comment-view',
                       kwargs={'pk': self.object.restaurant.pk})

    def get_initial(self):
        initial = super(CommentUpdate, self).get_initial()

        comment = get_object_or_404(Comment, pk=self.kwargs.get('pk'))

        initial['visitor'] = comment.visitor
        initial['email'] = comment.email
        initial['content'] = comment.content

        return initial

    def form_valid(self, form):
        comment = get_object_or_404(Comment, pk=self.kwargs.get('pk'))

        c = Comment(
            id=self.kwargs.get('pk'),
            visitor=comment.visitor,
            email=form.cleaned_data['email'],
            content=form.cleaned_data['content'],
            date_time=timezone.localtime(timezone.now()),
            restaurant=comment.restaurant
        )
        c.save()

        c.userUpVotes.clear()    # reset votes due to edit comment
        c.userDownVotes.clear()  # reset votes due to edit comment

        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        self.object = self.get_object()
        context = super(CommentUpdate, self).get_context_data(
            object=self.object, **kwargs)

        return context


class CommentDelete(PermissionMixin, DeleteView):

    model = Comment

    def get_success_url(self):
        return reverse('comment-view',
                       kwargs={'pk': self.object.restaurant.pk})


class CommentView(FormView, SingleObjectMixin):

    form_class = CommentForm
    template_name = 'comments.html'

    model = Restaurant         # provide by SingleObjectMixin
    context_object_name = 'r'  # provide by SingleObjectMixin

    def get_success_url(self):
        return reverse('comment-view',
                       kwargs={'pk': self.kwargs.get('pk')})

    def get_initial(self):
        initial = super(CommentView, self).get_initial()
        initial['visitor'] = self.request.user

        if self.request.user.is_authenticated():
            initial['email'] = self.request.user.email

        return initial

    def form_valid(self, form):
        Comment.objects.create(
            visitor=form.cleaned_data['visitor'],
            email=form.cleaned_data['email'],
            content=form.cleaned_data['content'],
            date_time=timezone.localtime(timezone.now()),
            restaurant=self.get_object()
            # don't need to add vote cause many to many field
            # M2M field operating after instance create
        )

        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):  # overide context_object_name var
        self.object = self.get_object()
        context = super(CommentView, self).get_context_data(
            object=self.object, **kwargs)

        return context

    def get_object(self, queryset=None):
        obj = super(CommentView, self).get_object(queryset=queryset)
        comments = obj.comment_set.all()

        for c in comments:
            c.thisUserUpVote = c.userUpVotes.filter(
                id=self.request.user.id).count()
            c.thisUserDownVote = c.userDownVotes.filter(
                id=self.request.user.id).count()
            c.save()

        return obj


def vote(request):

    thread_id = int(request.POST.get('id'))
    vote_type = request.POST.get('type')
    vote_action = request.POST.get('action')

    thread = get_object_or_404(Comment, pk=thread_id)

    thisUserUpVote = thread.userUpVotes.filter(id=request.user.id).count()
    thisUserDownVote = thread.userDownVotes.filter(id=request.user.id).count()

    if (vote_action == 'vote'):
        if (thisUserUpVote == 0) and (thisUserDownVote == 0):
            if (vote_type == 'up'):
                thread.userUpVotes.add(request.user)
            elif (vote_type == 'down'):
                thread.userDownVotes.add(request.user)
            else:
                return HttpResponse('error-unknown vote type')
        else:
            return HttpResponse('error - already voted')
    elif (vote_action == 'recall-vote'):
        if (vote_type == 'up') and (thisUserUpVote == 1):
            thread.userUpVotes.remove(request.user)
        elif (vote_type == 'down') and (thisUserDownVote == 1):
            thread.userDownVotes.remove(request.user)
        else:
            return HttpResponse(
                'error - unknown vote type or no vote to recall')
    else:
        return HttpResponse('error - bad action')

    num_votes = thread.userUpVotes.count() - thread.userDownVotes.count()

    thisUserUpVote = thread.userUpVotes.filter(id=request.user.id).count()
    thisUserDownVote = thread.userDownVotes.filter(id=request.user.id).count()

    return HttpResponse(num_votes)


def meta(request):
    values = request.META.items()
    values.sort()
    html = []
    for k, v in values:
        html.append('<tr><td>{0}</td><td>{1}</td></tr>'.format(k, v))
    return HttpResponse('<table>{0}</table>'.format('\n'.join(html)))


def set_c(request):
    response = HttpResponse('Set your lucky number as 8')
    response.set_cookie('lucky_number', 8)
    return response


def get_c(request):
    if 'lucky_number' in request.COOKIES:
        return HttpResponse('Your lucky number is {0}'.format(
                            request.COOKIES['lucky_number']))
    else:
        return HttpResponse('No Cookies.')


def use_session(request):
    request.session['lucky_number'] = 8  # set lucky number
    if 'lucky_number' in request.session:
        lucky_number = request.session['lucky_number']
        # read lucky number
        response = HttpResponse('Your lucky number is ' + str(lucky_number))
    del request.session['lucky_number']  # delete lucky number
    return response


def session_test(request):
    sid = request.COOKIES['sessionid']
    sid2 = request.session.session_key
    s = Session.objects.get(pk=sid)
    s_info = ('Session ID:' + sid + '<br>SessionID2:' + sid2 +
              '<br>Expire_date:' + str(s.expire_date) + '<br>Data:' +
              str(s.get_decoded()))
    return HttpResponse(s_info)

restaurants/templates/comment_update_form.html
{% extends "base.html" %}

{% block title %} Comment Update {% endblock %}

{% block content %}
    <form action="" method="post" class="form-horizontal" role="form" style="width:25%;margin:auto;text-align:left">{% csrf_token %}
        <table>
            <tr>
                <th style="text-align:left"><label for="id_visitor">留言者：</label></th>
            </tr>
            <tr>
                <td>{{ form.visitor }}</td>
            </tr>
            <tr>
                <td style="color:red;">{{ form.visitor.errors }}</td>
            </tr>
            <tr>
                <td><br></td>
            </tr>
            <tr>
                <th style="text-align:left"><label for="id_email">電子信箱：</label></th>
            </tr>
            <tr>
                <td>{{ form.email }}</td>
            </tr>
            <tr>
                <td style="color:red;">{{ form.email.errors }}</td>
            </tr>
            <tr>
                <td><br></td>
            </tr>
            <tr>
                <th style="text-align:left"><label for="id_content">評價：</label></th>
            </tr>
            <tr>
                <td>{{ form.content }}</td>
                <td style="color:red;">{{ form.content.errors }}</td>
            </tr>
            <tr>
                <td><br></td>
            </tr>
            <tr>
                <td style="text-align: center"><input type="submit"  value="給予評價" class="btn btn-default">&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;<a class="btn btn-default" href="{% url 'comment-view' c.restaurant.id %}">取消</a></td>
            </tr>
        </table>
    </form>
{% endblock %}

restaurants/templates/comments.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} Comment {% endblock %}

{% block css %}
    <style>
        .icon-in-button {
            padding: 2px 0px;
            width: 73px;
        }
        .icon-16 {
            height: 16px;
            width: 16px;
        }
        .icon-32 {
            height: 32px;
            width: 32px;
        }
    </style>
{% endblock %}

{% block content %}
                <a href="#add-comment" class="mvdot"><img src="{% static 'comment/add-comment.png' %}" alt="add-comment" height="88" width="88"></a>
                <h2>{{ r.name }}的評價</h2>
                {% if r.comment_set.all %}
                <p>目前共有{{ r.comment_set.all|length }}條評價</p>
                <table class="table table-hover" style="table-layout: fixed;word-break: break-all;">
                    <tr>
                        <th style="width:7%"></th>
                        <th style="width:20%">留言者</th>
                        <th style="width:20%">時間</th>
                        <th style="width:45%">評價</th>
                        <th style="width:8%"></th>
                    </tr>
                    
                    <img style="display:none" src="{% static 'vote/vote-down-off.png' %}" class="icon-32"/>
                    <img style="display:none" src="{% static 'vote/vote-down-on.png' %}" class="icon-32"/>
                    <img style="display:none" src="{% static 'vote/vote-up-off.png' %}" class="icon-32"/>
                    <img style="display:none" src="{% static 'vote/vote-up-on.png' %}" class="icon-32"/>
                    
                    {% for c in r.comment_set.all %}
                    <tr>
                        <td>
                            <!-- .votebuttons -->
                            <div class="vote-buttons">
                            <p>

                            {% ifequal c.thisUserUpVote 0 %}
                                <img class="vote-up {{ c.id }} icon-32" comment-id="{{ c.id }}"  src="{% static 'vote/vote-up-off.png' %}" title="Vote this thread UP. (click again to undo)" />
                            {% else %}
                                <img class="vote-up selected {{ c.id }} icon-32" comment-id="{{ c.id }}" src="{% static 'vote/vote-up-on.png' %}" title="Vote this thread UP. (click again to undo)" />
                            {% endifequal %}
                            </p>

                            <div class="vote-tally" style="font-size:1.5em;margin-bottom:8px;font-weight:bold;color:dimgrey;">
                                <span class="num {{c.id}}">{{ c.get_total_votes }}</span>
                            </div>

                            <p>
                            {% ifequal c.thisUserDownVote 0 %}
                                <img class="vote-down {{ c.id }} icon-32" comment-id="{{ c.id }}" src = "{% static 'vote/vote-down-off.png' %}" title="Vote this thread DOWN if it is innapropriate or incorrect. (click again to undo)" />
                            {% else %}
                                <img class="vote-down selected {{ c.id }} icon-32" comment-id="{{ c.id }}" src = "{% static 'vote/vote-down-on.png' %}" title="Vote this thread DOWN if it is innapropriate or incorrect. (click again to undo)" />
                            {% endifequal %}
                            </p>
                            </div>
                            <!-- .votebuttons -->
                        </td>
                        <td> {{ c.visitor }} </td>
                        <td> {{ c.date_time | date:"Y年n月j日 H:i" }} </td>
                        <td style="word-wrap:break-word;"> {{ c.content }} </td>
                        {% if request.user.is_authenticated and c.visitor == request.user.username %}
                            <td>
                                <a href="{% url 'comment-update' c.id %}" class="btn btn-warning icon-in-button" title="Comment Update link"><img src="{% static 'comment/edit.png' %}" alt="edit" class="icon-16">&nbsp;編輯</a><br><br>
                                <form action="{% url 'comment-delete' c.id %}" method="post">{% csrf_token %}
                                <button type="submit" class="btn btn-danger icon-in-button confirm-delete"><img src="{% static 'comment/delete.png' %}" alt="delete" class="icon-16">&nbsp;刪除</button>
                                </form>
                            </td>
                        {% else %}
                            <td></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                    
                </table>
                {% else %}
                <p>無評價</p>
                {% endif %}

                <br /><br />
                
                {% for e in errors %}
                    <p style="color:red;">{{ e }}</p>
                {% endfor %}

                <form id="add-comment" action="" method="post" class="form-horizontal" role="form" style="width:25%;margin:auto;text-align:left">{% csrf_token %}
                    <table>
                        <tr>
                            <th style="text-align:left"><label for="id_visitor">留言者：</label></th>
                        </tr>
                        <tr>
                            <td>{{ form.visitor }}</td>
                        </tr>
                        <tr>
                            <td style="color:red">{{ form.visitor.errors }}</td>
                        </tr>
                        <tr>
                            <td><br></td>
                        </tr>
                        <tr>
                            <th style="text-align:left"><label for="id_email">電子信箱：</label></th>
                        </tr>
                        <tr>
                            <td>{{ form.email }}</td>
                        </tr>
                        <tr>
                            <td style="color:red">{{ form.email.errors }}</td>
                        </tr>
                        <tr>
                            <td><br></td>
                        </tr>
                        <tr>
                            <th style="text-align:left"><label for="id_content">評價：</label></th>
                        </tr>
                        <tr>
                            <td>{{ form.content }}</td>
                            <td style="color:red">{{ form.content.errors }}</td>
                        </tr>
                        <tr>
                            <td><br></td>
                        </tr>
                        <tr>
                            <td><input type="submit" style="display: block;margin: auto" value="給予評價" class="btn btn-default"></td>
                        </tr>
                    </table>
                </form>
{% endblock %}

{% block javascript %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
<script>
    $.ajaxSetup({
        data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
    });
    
    $(document).ready(function() {
        
        $('div.bg').removeClass()
        
        $('.confirm-delete').click(function() {
            return confirm('Are you sure you want to delete this comment?');
        })

        $("div.vote-buttons img.vote-up").hover(
            function () { 
                var id = $(this).attr("comment-id");

                if (!$('.vote-down[comment-id="'+ id +'"]').hasClass('selected')) {
                    if ($(this).hasClass('selected')) {            
                        $(this).attr('src', '{% static 'vote/vote-up-off.png' %}'); 
                    }else{
                        $(this).attr('src', '{% static 'vote/vote-up-on.png' %}');
                    }
                }
            },
            function () { 
                var id = $(this).attr("comment-id");

                if (!$('.vote-down[comment-id="'+ id +'"]').hasClass('selected')) {
                    if ($(this).hasClass('selected')) {            
                        $(this).attr('src', '{% static 'vote/vote-up-on.png' %}'); 
                    }else{
                        $(this).attr('src', '{% static 'vote/vote-up-off.png' %}');
                    }
                }
            }
        );

        $("div.vote-buttons img.vote-down").hover(
            function () { 
                var id = $(this).attr("comment-id");

                if (!$('.vote-up[comment-id="'+ id +'"]').hasClass('selected')) {
                    if ($(this).hasClass('selected')) {            
                        $(this).attr('src', '{% static 'vote/vote-down-off.png' %}'); 
                    }else{
                        $(this).attr('src', '{% static 'vote/vote-down-on.png' %}');
                    }
                }
            },
            function () { 
                var id = $(this).attr("comment-id");

                if (!$('.vote-up[comment-id="'+ id +'"]').hasClass('selected')) {
                    if ($(this).hasClass('selected')) {            
                        $(this).attr('src', '{% static 'vote/vote-down-on.png' %}'); 
                    }else{
                        $(this).attr('src', '{% static 'vote/vote-down-off.png' %}');
                    }
                }
            }
        );
       
        var check_Login_Result = "{{request.user.is_authenticated}}";
        
        $('div.vote-buttons img.vote-up').click(function() {
            if (check_Login_Result != "True"){

                alert('Please login to vote!!');
                $(location).attr('href', '{% url 'accounts-login' %}')

            }else{

                var id = $(this).attr("comment-id");

                if (!$('.vote-down[comment-id="'+ id +'"]').hasClass('selected')) {

                    var vote_type = 'up';

                    if ($(this).hasClass('selected')) {

                        var vote_action = 'recall-vote';

                        $.post('/vote/', {id:id, type:vote_type, action:vote_action});
                        $('img.vote-up.'+id).removeAttr('src')
                            .attr('src', '{% static 'vote/vote-up-off.png' %}')
                            .removeClass('selected');

                        var $num = $('div.vote-tally span.num.'+id);
                        var num = parseInt($num.text(), 10);
                        $num.html(num - 1);

                    } else {

                        var vote_action = 'vote';

                        $.post('/vote/', {id:id, type:vote_type, action:vote_action}); 
                        $('img.vote-up.'+id).removeAttr('src')
                            .attr('src', '{% static 'vote/vote-up-on.png' %}')
                            .addClass('selected');

                        var $num = $('div.vote-tally span.num.'+id);
                        var num = parseInt($num.text(), 10);
                        $num.html(num + 1);

                    }
                }
            }
        });


        $('div.vote-buttons img.vote-down').click(function() {
            if (check_Login_Result != "True"){

                alert('Please login to vote!!');
                $(location).attr('href', '{% url 'accounts-login' %}')

            }else{

                var id = $(this).attr("comment-id");

                if (!$('.vote-up[comment-id="'+ id +'"]').hasClass('selected')) {

                    var vote_type = 'down';

                    if ($(this).hasClass('selected')) {

                        var vote_action = 'recall-vote';
                        $.post('/vote/', {id:id, type:vote_type, action:vote_action});

                        $('img.vote-down.'+id).removeAttr('src')
                            .attr('src', '{% static 'vote/vote-down-off.png' %}')
                            .removeClass('selected');

                        var $num = $('div.vote-tally span.num.'+id);
                        var num = parseInt($num.text(), 10);
                        $num.html(num + 1);

                    } else {

                        var vote_action = 'vote';
                        $.post('/vote/', {id:id, type:vote_type, action:vote_action}); 

                        $('img.vote-down.'+id).removeAttr('src')
                            .attr('src', '{% static 'vote/vote-down-on.png' %}')
                            .addClass('selected');

                        var $num = $('div.vote-tally span.num.'+id);
                        var num = parseInt($num.text(), 10);
                        $num.html(num - 1);

                    }
                }
            }
        });
    });

</script>
{% endblock %}

restaurants/templates/menu.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} Menu {% endblock %}

{% block css %}
    <style>
        .icon-24 {
            height: 24px;
            width: 24px;
        }
    </style>
{% endblock %}

{% block content %}
    {% load myfilters %}
    <h2>{{ restaurant.name }}的Menu</h2>
    {% if restaurant.food_set.all %}
    <p>本餐廳共有{{ restaurant.food_set.all|length }}道菜</p>
    <table class="table table-hover">
        <tr>
            <th>菜名</th>
            <th>價格</th>
            <th>辣不辣</th>
            <th>註解</th>
        </tr>
        {% for food in restaurant.food_set.all %}
        <tr>
            <td> {{ food.name }} </td>
            <td> {{ food.price }} </td>
            <td> {% if food.is_spicy %}
                     <img src="{% static 'spicy/spicy.png' %}" alt="spicy" class="icon-24">
                 {% else %}
                     不辣 
                 {% endif %}
            </td> 
            <td> {{ food.comment }} </td>
        </tr>
        {% endfor %}
    </table>
    </p>
    {% else %}
    <p>本餐廳啥都沒賣</p>
    {% endif %}
{% endblock %}

restaurants/templates/restaurants_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %} Restaurants {% endblock %}

{% block css %}
    <style>
        .icon-24 {
            height: 24px;
            width: 24px;
        }
    </style>
{% endblock %}

{% block content %}

                <h2>餐廳列表</h2>
                <br>
                <table class="table table-hover">
                    <tr>
                        <th>菜單</th>
                        <th>店名</th>
                        <th>電話</th>
                        <th>地址</th>
                        <th>評價</th>
                    </tr>
                    {% for r in restaurants %}
                    <tr>
                        <td><a href="/menu/{{r.id}}/" title="Menu link"><img src="{% static 'menu/menu-link.png' %}" alt="Menu Link" class="icon-24"></a></td>
                        <td> {{ r.name }}</td>
                        <td><a href="tel:{{ r.phone_number }}"><img src="{% static 'phone/phone-link.png' %}" alt="Phone Link" class="icon-24"/></a> {{ r.phone_number }}</td>
                        <td><a target="_blank" href="http://maps.google.com.tw/maps?q={{ r.address }}" title="Google Map link"><img src="{% static 'map/map-link.png' %}" alt="Map Link" class="icon-24"></a> {{ r.address }}</td>
                        <td><a href="/comment/{{r.id}}" title="Comment link"><img src="{% static 'comment/comment-link.png' %}" alt="Map Link" class="icon-24"></a> {{ r.comment_set.all|length }}條評價</td>
                    </tr>
                    {% endfor %}
                </table>

{% endblock %}

restaurants/templates/users_list.html
{% extends 'base.html' %}

{% block title %} User List {% endblock %}

{% block content %}
    <h2>使用者列表</h2>
    <br>
    <table class="table table-hover" style="text-align:center">
        <tr>
            <th>使用者帳號</th>
            <th>使用者上次登入時間</th>
        </tr>
        {% for u in users %}
            <tr>
                <td>{{ u.username }}</td>
                <td>{{u.last_login}}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}